name: wg-gui
include:
  - path: ./data/instances/1.yaml

services:
  wireguard_management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "wireguard_management"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./docker-compose.yaml:/app/docker-compose.yaml
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock
    ports:
      - 3000:3000
    networks:
      - wireguard_net

networks:
  wireguard_net:
    external: true
