export const CN_ZH = {
    wireguard_gui: 'Wireguard 管理界面',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP地址',
    allowed_source: '准许IP源',
    pub_key: '公共密钥',
    last_seen: '上一次握手',
    received: '接收',
    sent: '发送',
    received_data: '已接收数据',
    sent_data: '已发送数据',
    home: '主页',
    vpn_instances: 'VPN 实例',
    instance: '实例',
    interface: '网卡',
    last_couter_reset: '上一次计数器清零',
    user: '用户',
};

export const EN_GB = {
    wireguard_gui: 'Wireguard GUI',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP',
    allowed_source: 'Allowed Source',
    pub_key: 'Public Key',
    last_seen: 'Last Seen',
    received: 'Received',
    sent: 'Sent',
    received_data: 'Received Data',
    sent_data: 'Sent Data',
    home: 'Home',
    vpn_instances: 'VPN Instances',
    instance: 'Instance',
    interface: 'Interface',
    last_couter_reset: 'Last Counter Reset',
    user: 'User',
};
