export const CN_ZH = {
    wireguard_gui: 'WireGuard 管理界面',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP地址',
    allowed_source: '准许IP源',
    endpoint_ip: '对端地址',
    pub_key: '公共密钥',
    last_seen: '上一次握手',
    received: '接收',
    sent: '发送',
    received_data: '已接收数据',
    sent_data: '已发送数据',
    dashboard: '实例总览',
    vpn_instances: 'WireGuard 实例',
    instance: '实例',
    view_instance: '查看实例',
    load_balancer_ip: '负载均衡 IP',
    load_balancer_ip_auto: '由 MetalLB 池自动分配',
    load_balancer_ip_shared: '所有实例共享',
    listen_port_auto: '下一个空闲端口，自动分配',
    auto_assigned: '自动分配',
    last_counter_reset: '上一次计数器清零',
    user: '用户',
    add_user: '添加用户',
    description: '描述',
    allocated_ip: '分配 IP',
    allowed_ips: '允许 IP',
    private_key: '私钥',
    public_key: '公钥',
    generate_psk: '生成 PSK',
    download_config: '下载配置',
    show_qr: '显示二维码',
    copy_qr: '复制二维码',
    scan_hint: '使用 WireGuard 应用扫描，或导入下载的配置文件。',
    reload: '重载',
    psk: '预共享密钥',
    create_new_instance: '创建新实例',
    instance_name: '实例名称',
    server_vpn_subnet: 'VPN 子网',
    server_endpoint: '服务器端点',
    server_listen_port: '主机端口',
    server_public_key: '服务器公钥',
    dns: 'DNS',
    delete: '删除',
    confirm_delete: '删除此客户端？',
    cancel: '取消',
    edit: '编辑',
    save: '保存',
};

export const EN_GB = {
    wireguard_gui: 'WireGuard Management',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP',
    allowed_source: 'Allowed Source',
    endpoint_ip: 'Endpoint',
    pub_key: 'Public Key',
    last_seen: 'Last Seen',
    received: 'Received',
    sent: 'Sent',
    received_data: 'Received Data',
    sent_data: 'Sent Data',
    dashboard: 'Overview',
    vpn_instances: 'WG Instances',
    instance: 'Instance',
    view_instance: 'View Instance',
    load_balancer_ip: 'Load Balancer IP',
    load_balancer_ip_auto: 'Auto-assigned from the MetalLB pool',
    load_balancer_ip_shared: 'Shared by every instance',
    listen_port_auto: 'Next free port, auto-assigned',
    auto_assigned: 'Auto assigned',
    last_counter_reset: 'Last Counter Reset',
    user: 'User',
    add_user: 'Add User',
    description: 'Description',
    allocated_ip: 'Allocated IP',
    allowed_ips: 'Allowed IPs',
    private_key: 'Private Key',
    public_key: 'Public Key',
    generate_psk: 'Generate PSK',
    download_config: 'Download Config',
    show_qr: 'Show QR Code',
    copy_qr: 'Copy QR Code',
    scan_hint: 'Scan with the WireGuard app, or import the downloaded file.',
    reload: 'Reload',
    psk: 'Pre-shared Key',
    create_new_instance: 'Create New Instance',
    instance_name: 'Instance Name',
    server_vpn_subnet: 'VPN Subnet',
    server_endpoint: 'Server Endpoint',
    server_listen_port: 'Host Port',
    server_public_key: 'Server Public Key',
    dns: 'DNS',
    delete: 'Delete',
    confirm_delete: 'Delete this client?',
    cancel: 'Cancel',
    edit: 'Edit',
    save: 'Save',
};

export type LanguageKey = 'en' | 'zh';
export type Messages = typeof EN_GB;

export interface Language {
    key: LanguageKey;
    messages: Messages;
}

export const Language: Record<'EN' | 'ZH', Language> = {
    EN: { key: 'en', messages: EN_GB },
    ZH: { key: 'zh', messages: CN_ZH },
};

export const DEFAULT_LANGUAGE: Language = Language.EN;

export const LANGUAGE_STORAGE_KEY = 'wg-gui-language';
