export const CN_ZH = {
    wireguard_gui: 'Wireguard 管理界面',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP地址',
    allowed_source: '准许IP源',
    pub_key: '公共密钥',
    last_seen: '上一次握手',
    received: '接收',
    sent: '发送',
    received_data: '已接收数据',
    sent_data: '已发送数据',
    home: '主页',
    vpn_instances: 'VPN 实例',
    instance: '实例',
    load_balancer_ip: '负载均衡 IP',
    last_counter_reset: '上一次计数器清零',
    user: '用户',
    add_user: '添加用户',
    description: '描述',
    allocated_ip: '分配 IP',
    allowed_ips: '允许 IP',
    private_key: '私钥',
    public_key: '公钥',
    generate_psk: '生成 PSK',
    download_config: '下载配置',
    show_qr: '显示二维码',
    reload: '重载',
    psk: '预共享密钥',
    create_new_instance: '创建新实例',
    instance_name: '实例名称',
    server_vpn_ip: '服务器 VPN IP',
    server_endpoint: '服务器端点',
    server_listen_port: '主机端口',
    dns: 'DNS',
    delete: '删除',
    confirm_delete: '删除此客户端？',
    cancel: '取消',
    edit: '编辑',
    save: '保存',
};

export const EN_GB = {
    wireguard_gui: 'Wireguard GUI',
    users_registered: 'All Users on Interface wg0',
    ip: 'IP',
    allowed_source: 'Allowed Source',
    pub_key: 'Public Key',
    last_seen: 'Last Seen',
    received: 'Received',
    sent: 'Sent',
    received_data: 'Received Data',
    sent_data: 'Sent Data',
    home: 'Home',
    vpn_instances: 'VPN Instances',
    instance: 'Instance',
    load_balancer_ip: 'Load Balancer IP',
    last_counter_reset: 'Last Counter Reset',
    user: 'User',
    add_user: 'Add User',
    description: 'Description',
    allocated_ip: 'Allocated IP',
    allowed_ips: 'Allowed IPs',
    private_key: 'Private Key',
    public_key: 'Public Key',
    generate_psk: 'Generate PSK',
    download_config: 'Download Config',
    show_qr: 'Show QR Code',
    reload: 'Reload',
    psk: 'Pre-shared Key',
    create_new_instance: 'Create New Instance',
    instance_name: 'Instance Name',
    server_vpn_ip: 'Server VPN IP',
    server_endpoint: 'Server Endpoint',
    server_listen_port: 'Host Port',
    dns: 'DNS',
    delete: 'Delete',
    confirm_delete: 'Delete this client?',
    cancel: 'Cancel',
    edit: 'Edit',
    save: 'Save',
};

export const Language = Object.freeze({
    EN: Object.freeze({ key: 'en', messages: EN_GB }),
    ZH: Object.freeze({ key: 'zh', messages: CN_ZH }),
});

export const DEFAULT_LANGUAGE = Language.EN;

export const LANGUAGE_STORAGE_KEY = 'wg-gui-language';
